azblk handler: Version 1
gluster/nbd-runner pull request #74
Opened 2019-05-08 16:05 UTC by caavery

The azure page blob handler is based on and serves as a user-space
alternative to Khaled Henidak <khnidk@outlook.com> dysk kernel
block driver (https://github.com/khenidak/dysk).

azblk currently supports SAS access credentials, lease ids,
http, and https.

Signed-off-by: Cathy Avery <cavery@redhat.com>

2019-05-09 11:53 UTC, xiubli commented on handlers/Makefile.am
> +                               $(top_builddir)/utils/libutils.la
There is one extra white space before '$'.

2019-05-09 11:53 UTC, xiubli commented on handlers/Makefile.am
> +                               -I$(top_builddir)/ -I$(top_builddir)/utils      \
Same here.

2019-05-09 11:53 UTC, xiubli commented on handlers/Makefile.am
> +                               -I$(top_builddir)/daemon -I$(top_srcdir)/rpc
And here.

2019-05-09 11:53 UTC, xiubli commented on configure.ac
> +    fi
There has some extra white spaces before "fi".

2019-05-09 11:53 UTC, xiubli commented on cli/nbd-cli-azblk.c
> +
Please remove extra white line here.

2019-05-09 11:53 UTC, xiubli commented on cli/nbd-cli-azblk.c
> +};
You should also add the help message in nbd-runner/nbd-cli.c in:

```
[root@nbd-runner]# nbd-cli help
Usage:

	gluster help
		Display help for gluster commands

	ceph help [TODO]
		Display help for ceph commands

	global help [TODO]
		Display help for global commands

	version
		Display the version of nbd-cli

```

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +size_t get_blob_prop_headers(void *data, size_t size, size_t nitems, void *userp)
Should this also "static" ?

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +size_t get_callback(void *data, size_t size, size_t nmemb, void *userp)
static here too ?

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +    return 512;
Maybe you can just return 0 here if azure does not care about this and the NBD will set it to 512 or some other optimal size for you.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +    // nbd_err("NBD_CMD_DISCARD: req: %p, req->offset: %ld len: %ld\n", req, req->offset, req->len);
Maybe you can just uncommend it as one debug messages.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +static int azblk_read(struct nbd_handler_request *req)
Since the return value make no sense here it maybe just:

static void azblk_read() 
static void azblk_write() 
...
Will this make sense here ?

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +    // nbd_err("NBD_CMD_READ: req: %p, req->offset: %ld len: %ld\n", req, req->offset, req->len);
debug ?

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +                   void *userp, void *socketp)
Not aligned here.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +                 flags, &running_handles);
Not aligned here.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +                 uv_err_name(status));
Not aligned here.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +        struct azblk_dev *azdev)
Not aligned here.

2019-05-09 11:53 UTC, xiubli commented on handlers/azblk.c
> +    // nbd_err("NBD_CMD_DONE: req: %p, req->offset: %ld len: %ld\n", io_cb->nbd_req, io_cb->nbd_req->offset, io_cb->nbd_req->len);
Remove this or just as one debug messages ?

2019-05-09 12:40 UTC, caavery commented on handlers/azblk.c
> +                   void *userp, void *socketp)
static int azblk_handle_socket(CURL *curl_ezh, curl_socket_t s, int action,
                                                 void *userp, void *socketp

Is this what you want for alignment?

2019-05-09 12:42 UTC, caavery commented on handlers/azblk.c
> +                   void *userp, void *socketp)
Sorry it just right justified my code.
I spaced over the beginning of the second line 'v' under the 'C' in CURL

2019-05-09 13:14 UTC, lxbsz commented
@caavery 

Since this PR is still under reviewing and not merged, usually for any review changes we should fix them together with the previous commit without adding one extra new commit.

Then you can just do:
1, fix the review changes
2, # git add . && git commit --amend
3, # git push ${yourreponame} ${yourbranch}:azblk_1 --force

Thanks.
BRs

2019-05-09 13:17 UTC, lxbsz commented on handlers/azblk.c
> +                   void *userp, void *socketp)
It should be something like this as other code do:

```
static int azblk_handle_socket(CURL *curl_ezh, curl_socket_t s, int action,
                                                 void *userp, void *socketp
```

2019-05-09 13:35 UTC, caavery commented on handlers/azblk.c
> +                   void *userp, void *socketp)
ok thats what I did

2019-05-09 13:40 UTC, lxbsz commented on Dockerfile.buildtest
> +           libtirpc-devel rpcgen clang libuv libcurl   \
Here it should be libcurl-devel ?

2019-05-09 13:54 UTC, pkalever commented
@lxbsz 

Given that we have already discussed about the possibility of keeping nbd generic code hosting under gluster.org, we have decided that this should be moved to nbd base project [1] or elsewhere which actually makes much sense. There were many such discussions on bjns and private conversations etc, one such archival email at [2].

Because of this reason we are not socializing about nbd activity in any of our gluster-block channels yet.

Once we move this code to the relative project, we can resume the normal flow of work.

As discussed before, util then we should better freeze this just as it is as per the plan and back the repo locally.

I will have a discussion with the infra team tomorrow, about how to go forward from here and keep you guys updated about it.

[1] https://github.com/NetworkBlockDevice/nbd
[2] https://lists.gluster.org/pipermail//gluster-users/2019-March/036137.html

Thanks!

2019-05-09 14:01 UTC, lxbsz commented
> @lxbsz
> 
> Given that we have already discussed about the possibility of keeping nbd generic code hosting under gluster.org, we have decided that this should be moved to nbd base project [1] or elsewhere which actually makes much sense. There were many such discussions on bjns and private conversations etc, one such archival email at [2].
> 
> Because of this reason we are not socializing about nbd activity in any of our gluster-block channels yet.
> 
> Once we move this code to the relative project, we can resume the normal flow of work.
> 
> As discussed before, util then we should better freeze this just as it is as per the plan and back the repo locally.
> 
> I will have a discussion with the infra team tomorrow, about how to go forward from here and keep you guys updated about it.
> 
> [1] https://github.com/NetworkBlockDevice/nbd
> [2] https://lists.gluster.org/pipermail//gluster-users/2019-March/036137.html
> 
> Thanks!

@pkalever 
This is still underway and not finished yet.

Thanks.

2019-05-09 14:12 UTC, pkalever requested changes
@lxbsz requesting changes to the project infra as mentioned at https://github.com/gluster/nbd-runner/pull/74#issuecomment-490914747

2019-05-09 14:33 UTC, lxbsz commented
> @lxbsz requesting changes to the project infra as mentioned at [#74 (comment)](https://github.com/gluster/nbd-runner/pull/74#issuecomment-490914747)

@pkalever 

No Problem Prasanna :-)
Once that is done and will host it in other place.

Thanks.
BRs

2019-05-09 22:09 UTC, amarts commented
> Because of this reason we are not socializing about nbd activity in any of our gluster-block channels yet.
> 
> Once we move this code to the relative project, we can resume the normal flow of work.
> 
> As discussed before, util then we should better freeze this just as it is as per the plan and back the repo locally.

@pkalever @lxbsz I would prefer to not ignore/block the work someone else, outside of @gluster/gluster-all  has contributed in Gluster.org projects, due to process. While we get into the process of migration, I suggest to keep moving on!

2019-05-10 07:13 UTC, lxbsz commented
> > Because of this reason we are not socializing about nbd activity in any of our gluster-block channels yet.
> > Once we move this code to the relative project, we can resume the normal flow of work.
> > As discussed before, util then we should better freeze this just as it is as per the plan and back the repo locally.
> 
> @pkalever @lxbsz I would prefer to not ignore/block the work someone else, outside of @gluster/gluster-all has contributed in Gluster.org projects, due to process. While we get into the process of migration, I suggest to keep moving on!

Yeah, make sense to me.

Thanks.

2019-05-10 14:18 UTC, merged